name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    container:
      image: kivy/buildozer:latest

    env:
      BUILDOZER_WARN_ON_ROOT: 0

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build APK
        run: |
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: PrayerAlarmPro-APK
          path: bin/*.apk